### ISSUE TITLE
Allow selecting a database to run in

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter.VisualStudio#19]
Running application from VS always uses default database. It makes it unusable in case you use multiple databases. That should be an easily changeable option. It would be best if it could appear (only if there are multiple dbs) beside other debugging options in VS:
![image](https://cloud.githubusercontent.com/assets/6013217/26719460/e6677cc6-4784-11e7-8253-cc0a1f593e74.png)

**Comment by per-samuelsson** [comment]
You can do this by using `Project properties | Debug | Command-line options`. It accept basically everything `star.exe` does, including `-d=mydb`.

**Comment by joozek78** [comment]
Great! ~~I'll add an issue for easy switcher!~~ it's easy enough as it is :)
