### ISSUE TITLE
VS Extenstion "More Info" link leads to a 404

### ISSUE THREAD

**Issue by alshakero** [Starcounter/Starcounter.VisualStudio#20]
![image](https://user-images.githubusercontent.com/17054134/26871589-08893edc-4b74-11e7-922d-a2456d696bf9.png)

Leads to https://docs.starcounter.io/guides/working-with-starcounter/visual-studio-extension/

/cc @Mackiovello

**Comment by ErlendLandro** [comment]
Thank you for noting! Fixed with 	69aede2
