### ISSUE TITLE
Add a comment in HTML template that `<dom-bind>` is a Polymer element

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter.VisualStudio#22]
Add a comment in https://github.com/Starcounter/Starcounter.VisualStudio/blob/develop/src/Starcounter.VS.HTMLTemplateItemTemplate/HTMLTemplate.html saying that `dom-bind` is a Polymer auto-binding template.

This will help new developers who have problems seeing the difference between what is Starcounter and what is Polymer.

WDYT @Mackiovello, @mmnosek

**Comment by mmnosek** [comment]
👍  from me. Most of the people have no idea what Polymer is and they may think it's something Starcounter-specific. We want to avoid such impression.

**Comment by alshakero** [comment]
Done in https://github.com/Starcounter/Starcounter.VisualStudio/pull/23

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/Starcounter.VisualStudio/pull/23

**Comment by warpech** [comment]
@ubbeK how is this released? Does someone manually release a new version of the Visual Studio extension?

**Comment by ubbeK** [comment]
Yes, I think so. I have never done it though.

cc @per-samuelsson

**Comment by warpech** [comment]
This can't be moved to "Finish" until https://github.com/Starcounter/Starcounter.VisualStudio/issues/27 is resolved.
