### ISSUE TITLE
Project templates for 2.4 is broken

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter.VisualStudio#24]
By chance, I noticed project templates for 2.4 was broken some time ago: my guess is they were just brutally overwritten by a forcing merge from master-develop.

First, extension version was changed from 2.0 -> 1.0 in this commit: https://github.com/Starcounter/Starcounter.VisualStudio/commit/f0da05583130cdc3ea95a33418a6ca1a63afd945. This seem to later have been fixed by @ubbeK.

Then templates where broken in this commit: https://github.com/Starcounter/Starcounter.VisualStudio/commit/8a811c6160c7e256b3119f48ffd90199a89ac0fc. At least the application project in this diff: https://github.com/Starcounter/Starcounter.VisualStudio/commit/8a811c6160c7e256b3119f48ffd90199a89ac0fc#diff-0e1b02766b835ae4d835d89000dec255

cc @threezool

**Comment by ubbeK** [comment]
Yes, I remember I did some fix there. 

Note that threezool is not with us anymore.

**Comment by per-samuelsson** [comment]
> Note that threezool is not with us anymore.

Yeah, thanks, @miyconst informed me and hence I assigned it to me.

**Comment by per-samuelsson** [comment]
Reviewed the code and as far as I can tell, this was solved when we went to one single extension.
