### ISSUE TITLE
Update dom-bind template for Polymer 2

### ISSUE THREAD

**Issue by alshakero** [Starcounter/Starcounter.VisualStudio#25]
As in move from
```html
<template>
    <template is="dom-bind">
        ...
    </template>
</template>
```

To 
```html
<template>
    <dom-bind>
        <!-- `is` attribute is optional for Polymer 1 backwards compatibility -->
		<template is="dom-bind">
			...
		</template>
     </dom-bind>
</template>
```

**Comment by warpech** [comment]
@PatrykSzwer can you pls do it? @alshakero will review.

**Comment by warpech** [comment]
After it is done please ping @ubbeK to release a new version of the extension.

**Comment by warpech** [comment]
Closing as done in #26

**Comment by warpech** [comment]
Release in Visual Studio marketplace is tracked in https://github.com/Starcounter/Starcounter.VisualStudio/issues/27

**Comment by warpech** [comment]
Can be marked as Finished when the extension is installable in Visual Studio (see https://github.com/Starcounter/Starcounter.VisualStudio/issues/27#issuecomment-356971462).
