### ISSUE TITLE
Publish "Starcounter 2.4 for Visual Studio" in the Marketplace

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter.VisualStudio#28]
Since Visual Studio Marketplace only supports one version at the time ([source](https://github.com/Starcounter/Starcounter.VisualStudio/wiki/Version-compatibility#i-cant-find-version-2x-of-the-extension-on-the-visual-studio-marketplace)), I suggest we bypass it by publishing another extension called "Starcounter 2.4 for Visual Studio".

Then we can switch the installer of Starcounter 2.4 to offer installing that version of the extension.

This is [how NUnit solves it](https://marketplace.visualstudio.com/search?term=nunit%20test%20adapter&target=VS&category=All%20categories&vsVersion=&sortBy=Relevance), among others.

We are getting more and more partners using Starcounter 2.4 and we want them to be able to use the stuff that we work on.

WDYT @ubbeK, @per-samuelsson?

**Comment by per-samuelsson** [comment]
> WDYT @ubbeK, @per-samuelsson?

SGTM. I actually never considered that.

One thing though: since the aim is we want to merge versions, so we have only **one** extension version, maybe we should consider that already now, when doing naming? Like "what's our strategy the day we complete that merge"? 

I guess, in the scheme you propose, we simply just delete "Starcounter 2.4 for Visual Studio" at that point? Are there better ways to name it? Like we named it "next" or "beta" or whatever, stating that this will in fact become the sole version eventually?

**Comment by warpech** [comment]
Actually no, in the scheme that I propose, the current extension "Starcounter for Visual Studio" will forever be for Starcounter 2.3 (we can rename it to "Starcounter 2.3 for Visual Studio").

So for every breaking change version of Starcounter we will have a separate Visual Studio extension.

**Comment by per-samuelsson** [comment]
> Actually no, in the scheme that I propose, the current extension "Starcounter for Visual Studio" will forever be for Starcounter 2.3 (we can rename it to "Starcounter 2.3 for Visual Studio").

Exactly, I wonder if that approach is not better.

My main objective here is that we should think it through an extra time and find the scheme that best align with the fact that (hopefully pretty soon) we'll have just a single version of the extension.

**Comment by ubbeK** [comment]
This VisualStudio extension will most likely be splitted up into two different VS marketplace extensions, according to @warpech and @per-samuelsson discussion. 

* Current extension `Starcounter for Visual Studio` will be using https://www.nuget.org/packages/Starcounter.VisualStudio/1.0.4
* 2.4 extension will be using https://www.nuget.org/packages/Starcounter.VisualStudio/2.1.0

But what should the 2.4 version be called? Rename the current one?

cc @miyconst

**Comment by ubbeK** [comment]
~~@iqbal will update the current extension in this issue: https://github.com/Starcounter/Starcounter.VisualStudio/issues/27~~

Edited: that was wrong. The new version should be updated there.

**Comment by ubbeK** [comment]
Decided on last [ReleasePlanning](https://github.com/Starcounter/Minutes/issues/136) meeting:

* Current extension will still be called `Starcounter for Visual Studio` and will target https://www.nuget.org/packages/Starcounter.VisualStudio/1.0.4
* New extension will be called `Starcounter 2.4 for Visual Studio` and will target https://www.nuget.org/packages/Starcounter.VisualStudio/2.1.0

**Comment by ubbeK** [comment]
@iqbalskd Before doing this issue, please release new 1.0.5 nuget package, https://github.com/Starcounter/Starcounter.VisualStudio/issues/35, and make sure tag `Starcounter for Visual Studio` targets that package.

**Comment by miyconst** [comment]
Won't this issue resolved by implementing support for `2.3` and `2.4` Starcounter version into the same extension?

**Comment by iqbalskd** [comment]
This issue has been done by combining vs extentions for both `2.3` and `2.4`. So closing it
