### ISSUE TITLE
Release a new nuget package for master branch

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/Starcounter.VisualStudio#35]
There have been some new commits, release a new nuget package, `version: 1.0.5` (master branch)

Make sure to 
* bump version to `1.0.5`: https://github.com/Starcounter/Starcounter.VisualStudio/blob/master/build/version.txt
* create a git tag: `v1.0.5`

**Comment by iqbalskd** [comment]
@ubbeK 

- Released a new version
- Published the nuget package.
- Uploaded to VS Marketplace.
