### ISSUE TITLE
Wrong version installed by Starcounter installer

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter.VisualStudio#39]
Starcounter installer installs the version 2.0.0 of VS extension, which fails to work with the app projects.

The current version of the extension in VS marketplace is 3.0.1. To replace 2.0.0 with 3.0.1, I need to manually uninstall 2.0.0, restart VS, and then install 3.0.1.

I guess that I should get from the installer this version or nothing.

**Comment by ubbeK** [comment]
@iqbalskd

**Comment by iqbalskd** [comment]
Added the latest Starcounter.VisualStudio as nuget package in `Starcounter.InstallerEngine` project.
Closing this as done.
